name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install & build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # 4) Upload the dist/ folder as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # 5) Deploy to GitHub Pages via API
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
